SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE TABLE IF NOT EXISTS `spl`.`msg_messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `thread_id` INT(11) NOT NULL,
  `body` TEXT NOT NULL,
  `priority` INT(2) NOT NULL DEFAULT '0',
  `sender_id` INT(11) NOT NULL,
  `cdate` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `spl`.`msg_participants` (
  `user_id` INT(11) NOT NULL,
  `thread_id` INT(11) NOT NULL,
  `cdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`, `thread_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `spl`.`msg_status` (
  `message_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `status` INT(2) NOT NULL,
  PRIMARY KEY (`message_id`, `user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `spl`.`msg_threads` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `subject` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
