SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `spl`.`matches` 
ADD COLUMN `home_team_ban_hero_id` INT(11) NULL DEFAULT NULL AFTER `strife_match_id`,
ADD COLUMN `away_team_ban_hero_id` VARCHAR(45) NULL DEFAULT NULL AFTER `home_team_ban_hero_id`,
ADD COLUMN `server_region` VARCHAR(45) NULL DEFAULT NULL AFTER `away_team_ban_hero_id`,
ADD COLUMN `length` INT(11) NULL DEFAULT NULL AFTER `server_region`,
ADD COLUMN `replay_processed` TINYINT(4) NULL DEFAULT '0' AFTER `length`;

ALTER TABLE `spl`.`stats` 
ADD COLUMN `advanced` SMALLINT(6) NULL DEFAULT '0' AFTER `pet_id`,
ADD COLUMN `total_gold` INT(11) NULL DEFAULT NULL AFTER `advanced`,
ADD COLUMN `total_creep` INT(11) NULL DEFAULT NULL AFTER `total_gold`,
ADD COLUMN `total_neut` INT(11) NULL DEFAULT NULL AFTER `total_creep`,
ADD COLUMN `kills` INT(11) NULL DEFAULT NULL AFTER `total_neut`,
ADD COLUMN `assists` INT(11) NULL DEFAULT NULL AFTER `kills`,
ADD COLUMN `deaths` INT(11) NULL DEFAULT NULL AFTER `assists`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
