SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


CREATE TABLE IF NOT EXISTS `looking_for_players` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `team_id` INT(11) NOT NULL,
  `bot` INT(11) NULL DEFAULT NULL,
  `mid` INT(11) NULL DEFAULT NULL,
  `top` INT(11) NULL DEFAULT NULL,
  `carry` INT(11) NULL DEFAULT NULL,
  `init` INT(11) NULL DEFAULT NULL,
  `caster` INT(11) NULL DEFAULT NULL,
  `utility` INT(11) NULL DEFAULT NULL,
  `tank` VARCHAR(45) NULL DEFAULT NULL,
  `desc` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

ALTER TABLE `matches` 
ADD COLUMN `match_type` INT(11) NULL DEFAULT NULL AFTER `proposeddate_timestamp`;

CREATE TABLE IF NOT EXISTS `team_invites` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `invite_type` INT(11) NOT NULL,
  `team_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `sender_id` INT(11) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;

ALTER TABLE `teams` 
ADD COLUMN `active` INT(11) NULL DEFAULT NULL AFTER `id`,
ADD COLUMN `invites` INT(11) NULL DEFAULT NULL AFTER `region`;

CREATE TABLE IF NOT EXISTS `users_extra` (
  `id` INT(11) UNSIGNED NOT NULL,
  `region` VARCHAR(15) NULL DEFAULT 'Unknown',
  `bio` VARCHAR(1000) NULL DEFAULT NULL,
  `contact_twitter` VARCHAR(45) NULL DEFAULT NULL,
  `contact_facebook` VARCHAR(45) NULL DEFAULT NULL,
  `contact_twitch` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_extra_1`
    FOREIGN KEY (`id`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


DELIMITER $$

USE `spl-prod`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `users_AINS`
AFTER INSERT ON `users`
FOR EACH ROW
BEGIN
	INSERT into `users_extra` SET id = NEW.id;
END$$


DELIMITER ;

INSERT INTO `heroes` (`name`) VALUES ('Hero_Trixie');
INSERT INTO `heroes` (`name`) VALUES ('Hero_Blazer');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
