SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `lobby_players` 
ADD COLUMN `team1_vote` SMALLINT(6) NULL DEFAULT NULL AFTER `change`,
ADD COLUMN `team2_vote` SMALLINT(6) NULL DEFAULT NULL AFTER `team1_vote`;

ALTER TABLE `lobbys` 
ADD COLUMN `team2_votes` SMALLINT(6) NOT NULL DEFAULT '0' AFTER `inprogress`;

ALTER TABLE `matches` 
CHANGE COLUMN `home_team_points` `home_team_points` INT(11) NOT NULL DEFAULT '0' ,
CHANGE COLUMN `away_team_points` `away_team_points` INT(11) NOT NULL DEFAULT '0' ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
